// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CommPadd {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("Home")]
	public partial class Home {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_StatusLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("StatusLabel")]
		private MonoTouch.UIKit.UILabel StatusLabel {
			get {
				this.__mt_StatusLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("StatusLabel")));
				return this.__mt_StatusLabel;
			}
			set {
				this.__mt_StatusLabel = value;
				this.SetNativeField("StatusLabel", value);
			}
		}
	}
}
