// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CommPadd {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MainLcars")]
	public partial class MainLcars {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private LcarsComp __mt_RelativeComp;
		
		private LcarsComp __mt_Comp1;
		
		private LcarsComp __mt_Comp7;
		
		private LcarsComp __mt_Comp2;
		
		private LcarsComp __mt_MiscComp;
		
		private LcarsComp __mt_Comp6;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("RelativeComp")]
		private LcarsComp RelativeComp {
			get {
				this.__mt_RelativeComp = ((LcarsComp)(this.GetNativeField("RelativeComp")));
				return this.__mt_RelativeComp;
			}
			set {
				this.__mt_RelativeComp = value;
				this.SetNativeField("RelativeComp", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("Comp1")]
		private LcarsComp Comp1 {
			get {
				this.__mt_Comp1 = ((LcarsComp)(this.GetNativeField("Comp1")));
				return this.__mt_Comp1;
			}
			set {
				this.__mt_Comp1 = value;
				this.SetNativeField("Comp1", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("Comp7")]
		private LcarsComp Comp7 {
			get {
				this.__mt_Comp7 = ((LcarsComp)(this.GetNativeField("Comp7")));
				return this.__mt_Comp7;
			}
			set {
				this.__mt_Comp7 = value;
				this.SetNativeField("Comp7", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("Comp2")]
		private LcarsComp Comp2 {
			get {
				this.__mt_Comp2 = ((LcarsComp)(this.GetNativeField("Comp2")));
				return this.__mt_Comp2;
			}
			set {
				this.__mt_Comp2 = value;
				this.SetNativeField("Comp2", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("MiscComp")]
		private LcarsComp MiscComp {
			get {
				this.__mt_MiscComp = ((LcarsComp)(this.GetNativeField("MiscComp")));
				return this.__mt_MiscComp;
			}
			set {
				this.__mt_MiscComp = value;
				this.SetNativeField("MiscComp", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("Comp6")]
		private LcarsComp Comp6 {
			get {
				this.__mt_Comp6 = ((LcarsComp)(this.GetNativeField("Comp6")));
				return this.__mt_Comp6;
			}
			set {
				this.__mt_Comp6 = value;
				this.SetNativeField("Comp6", value);
			}
		}
	}
}
