// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CommPadd {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MessageReader")]
	public partial class MessageReader {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private LcarsComp __mt_RelativeComp;
		
		private LcarsComp __mt_TopBtn;
		
		private MonoTouch.UIKit.UIWebView __mt_TextBox;
		
		private LcarsComp __mt_OriginalBtn;
		
		private LcarsComp __mt_CloseBtn;
		
		private LcarsComp __mt_BottomBtn;
		
		private LcarsComp __mt_PlayBtn;
		
		private LcarsComp __mt_ShareBtn;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("RelativeComp")]
		private LcarsComp RelativeComp {
			get {
				this.__mt_RelativeComp = ((LcarsComp)(this.GetNativeField("RelativeComp")));
				return this.__mt_RelativeComp;
			}
			set {
				this.__mt_RelativeComp = value;
				this.SetNativeField("RelativeComp", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TopBtn")]
		private LcarsComp TopBtn {
			get {
				this.__mt_TopBtn = ((LcarsComp)(this.GetNativeField("TopBtn")));
				return this.__mt_TopBtn;
			}
			set {
				this.__mt_TopBtn = value;
				this.SetNativeField("TopBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TextBox")]
		private MonoTouch.UIKit.UIWebView TextBox {
			get {
				this.__mt_TextBox = ((MonoTouch.UIKit.UIWebView)(this.GetNativeField("TextBox")));
				return this.__mt_TextBox;
			}
			set {
				this.__mt_TextBox = value;
				this.SetNativeField("TextBox", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("OriginalBtn")]
		private LcarsComp OriginalBtn {
			get {
				this.__mt_OriginalBtn = ((LcarsComp)(this.GetNativeField("OriginalBtn")));
				return this.__mt_OriginalBtn;
			}
			set {
				this.__mt_OriginalBtn = value;
				this.SetNativeField("OriginalBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CloseBtn")]
		private LcarsComp CloseBtn {
			get {
				this.__mt_CloseBtn = ((LcarsComp)(this.GetNativeField("CloseBtn")));
				return this.__mt_CloseBtn;
			}
			set {
				this.__mt_CloseBtn = value;
				this.SetNativeField("CloseBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("BottomBtn")]
		private LcarsComp BottomBtn {
			get {
				this.__mt_BottomBtn = ((LcarsComp)(this.GetNativeField("BottomBtn")));
				return this.__mt_BottomBtn;
			}
			set {
				this.__mt_BottomBtn = value;
				this.SetNativeField("BottomBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("PlayBtn")]
		private LcarsComp PlayBtn {
			get {
				this.__mt_PlayBtn = ((LcarsComp)(this.GetNativeField("PlayBtn")));
				return this.__mt_PlayBtn;
			}
			set {
				this.__mt_PlayBtn = value;
				this.SetNativeField("PlayBtn", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("ShareBtn")]
		private LcarsComp ShareBtn {
			get {
				this.__mt_ShareBtn = ((LcarsComp)(this.GetNativeField("ShareBtn")));
				return this.__mt_ShareBtn;
			}
			set {
				this.__mt_ShareBtn = value;
				this.SetNativeField("ShareBtn", value);
			}
		}
	}
}
