// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CommPadd {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SourceTypeMessages")]
	public partial class SourceTypeMessages {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITableView __mt_MsgTable;
		
		private MonoTouch.UIKit.UILabel __mt_DateHead;
		
		private MonoTouch.UIKit.UILabel __mt_SubHead;
		
		private MonoTouch.UIKit.UILabel __mt_DisHead;
		
		private MonoTouch.UIKit.UILabel __mt_FromHead;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("MsgTable")]
		private MonoTouch.UIKit.UITableView MsgTable {
			get {
				this.__mt_MsgTable = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("MsgTable")));
				return this.__mt_MsgTable;
			}
			set {
				this.__mt_MsgTable = value;
				this.SetNativeField("MsgTable", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("DateHead")]
		private MonoTouch.UIKit.UILabel DateHead {
			get {
				this.__mt_DateHead = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("DateHead")));
				return this.__mt_DateHead;
			}
			set {
				this.__mt_DateHead = value;
				this.SetNativeField("DateHead", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("SubHead")]
		private MonoTouch.UIKit.UILabel SubHead {
			get {
				this.__mt_SubHead = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("SubHead")));
				return this.__mt_SubHead;
			}
			set {
				this.__mt_SubHead = value;
				this.SetNativeField("SubHead", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("DisHead")]
		private MonoTouch.UIKit.UILabel DisHead {
			get {
				this.__mt_DisHead = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("DisHead")));
				return this.__mt_DisHead;
			}
			set {
				this.__mt_DisHead = value;
				this.SetNativeField("DisHead", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("FromHead")]
		private MonoTouch.UIKit.UILabel FromHead {
			get {
				this.__mt_FromHead = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("FromHead")));
				return this.__mt_FromHead;
			}
			set {
				this.__mt_FromHead = value;
				this.SetNativeField("FromHead", value);
			}
		}
	}
}
